"""Generated by Django 5.1.2 on 2024-11-08 13:06."""

from django.db import migrations
from django.utils import timezone


def create_superuser(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    """Create the superuser if they do not already exist.

    Called by the data migration, this function checks if the 'admin' user already
    exists in the database. If they do not, then a new superuser is created and
    saved to the database.

    :param apps: The Django apps registry.
    :type apps: django.apps.registry.Apps

    :param schema_editor: The database schema editor.
    :type schema_editor: django.db.backends.base.schema.BaseDatabaseSchemaEditor
    """
    from django.contrib.auth import get_user_model

    User = get_user_model()  # noqa: N806

    if User.objects.filter(username="admin").exists():
        return  # admin already exists

    superuser = User.objects.create_superuser(
        username="admin",
        email="admin@localhost",
        password="admin",  # noqa: S106
        last_login=timezone.now())

    superuser.save()

class Migration(migrations.Migration):  # noqa: D101

    dependencies = [  # noqa: RUF012
        ("app", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.RunPython(create_superuser),
    ]


