# Generated by Django 5.1.2 on 2024-11-21 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_userprofile_options_alter_userprofile_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
